### ISSUE TITLE
Construir la imagen de contenedor para admitir las plataformas linux/amd64 y linux/arm64

### ISSUE THREAD

**Issue by xcloady** [jrbalsas/asnwebapps#10]
Debido a la emergente arquitectura de los equipos con procesadores de la serie M de Apple, sería conveniente realizar la construcción de la imagen de contenedor para esa arquitectura (linux/arm64). 

https://github.com/jrbalsas/asnwebapps/blob/15f0170242646515f66f087ae9d610344acd611f/k8s/testapp-waf/waf-modsecurity.yaml#L19C1-L19C43

De forma temporal, he creado una imagen de contenedor que solventa el problema para esta arquitectura desde el repositorio xcloady/modsecurity ([https://hub.docker.com/r/xcloady/modsecurity/tags](https://hub.docker.com/r/xcloady/modsecurity/tags)).

**Comment by jrbalsas** [comment]
¿Has podido recrear la imagen usando el fichero Dockerfile disponible en [k8s/waf](https://github.com/jrbalsas/asnwebapps/tree/master/k8s/waf) o has utilizado otra imagen base?

**Comment by xcloady** [comment]
He tenido que utilizar la imagen base del repositorio [vshn/modsecurity-docker](https://github.com/vshn/modsecurity-docker)

**Comment by jrbalsas** [comment]
Sí, claro, pero observa la configuración específica que hay en el fichero Dockerfile que te he comentado ya que hay algunas reglas que hay que desactivar para evitar algunos falsos positivos que pueden daros problemas, sobre todo si finalmente desplegáis en GKE

**Comment by jrbalsas** [comment]
Añadido fichero README.md para aclarar cómo adaptar el WAF para soporte arm64  d2cd142. Gracias por el aviso
